# Generated by Django 3.1.7 on 2021-05-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210512_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regis',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='regis',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
