# Generated by Django 3.1.7 on 2021-05-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210513_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='boletos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
            ],
        ),
    ]
