# Generated by Django 3.1.7 on 2021-05-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_boletos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletos',
            name='descuento',
        ),
        migrations.AddField(
            model_name='boletos',
            name='Descuento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='boletos',
            name='Valor_Descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
