# Generated by Django 3.1.7 on 2021-05-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210515_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletos',
            old_name='Valor_Descuento',
            new_name='Valor',
        ),
    ]
