# Generated by Django 3.1.7 on 2021-05-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210515_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletos',
            old_name='Descuento',
            new_name='Usuario',
        ),
        migrations.RemoveField(
            model_name='boletos',
            name='Valor',
        ),
        migrations.RemoveField(
            model_name='boletos',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='boletos',
            name='total',
        ),
    ]
