# Generated by Django 3.1.7 on 2021-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_boletos_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletos',
            name='Descuento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
