# Generated by Django 3.1.7 on 2021-05-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_boletos_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletos',
            name='Usuario',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
